### ISSUE TITLE
大神，preprocessing库是什么呀？

### ISSUE THREAD

**Issue by Runkun-Lu** [duxuhao/Feature-Selection#1]
大神，你导入的preprocessing库怎么安装呀？

**Comment by duxuhao** [comment]
你好，我自己写的库，和特征相关的一些东西，其实不是必要的库。

新上传的版本已经修复好了，因为之前在本地测所以没发现这个bug，不好意思。

谢谢支持！

**Comment by Runkun-Lu** [comment]
哦哦，好的，谢谢啦
