### ISSUE TITLE
算法是不是有点小bug？

### ISSUE THREAD

**Issue by aa147138** [duxuhao/Feature-Selection#11]
![qq 20180809125633](https://user-images.githubusercontent.com/37172475/43878822-ba4f7ba8-9bd3-11e8-9cbf-711b05ccad8a.png)
您好，代码里面是不是要加上我用红框框出来的那一句代码？因为 _df 删除 newcolname之后，selectcol如果不同步删除的话，会出现 selectcol 里面的字段 _df没有的情况，然后  X.ix[train_index,:][features] 这个地方会报错。我的理解是否正确？

**Comment by aa147138** [comment]
之前放的图片没有显示出来，放一下代码
                    if self._ScoreUpdate():
                        Effective.append(newcolname)
                    else:
                        self._df.drop(newcolname, axis = 1, inplace=True)
                        selectcol.remove(newcolname)         #这个地方加上这一句

**Comment by duxuhao** [comment]
谢谢您的提点，确实是这样，已经修复了！
