### ISSUE TITLE
Whether to support Chinese feature names？

### ISSUE THREAD

**Issue by renxingkai** [duxuhao/Feature-Selection#15]
Thank you so much for your contribution. Today, I use it for a Chinese dataset which the columns name are Chinese. However, it broken down and output the infomation "_UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-13: ordinal not in range(128)_". I want to know whether the tools support the Chinese feature names?

**Comment by duxuhao** [comment]
I don't think it support Chinese column name so far. Sorry about that.
