### ISSUE TITLE
这个可以跟Kflod结合吗？

### ISSUE THREAD

**Issue by Lvnszn** [duxuhao/Feature-Selection#3]
这个可以跟Kflod结合使用的话，会不会效果不好？

**Comment by duxuhao** [comment]
实际上是可以和kfold结合的，我晚上上传一个例子，通过用在简单的titanic数据集上并使用kfold的版本

**Comment by Lvnszn** [comment]
多谢，我已经写了一个，并且跑起来了。~

**Comment by Lvnszn** [comment]
话说300多个特征，会不会执行的很慢。。

**Comment by duxuhao** [comment]
已经添加一个简单的demo了，谢谢你的反馈！

如果是这次ijcai的数据集的话是会花点时间，但是基本上你能随时中断它，中断后你可以手动再添加你自己觉得很有用的特征再重新开始搜索。如果是小或者中等大小的数据集就会跑的很快
