### ISSUE TITLE
运行代码显示'MLFeatureSelection' has no attribute 'Select'

### ISSUE THREAD

**Issue by RainFung** [duxuhao/Feature-Selection#4]
AttributeError                            Traceback (most recent call last)
<ipython-input-6-e399e2b5b40c> in <module>()
     11 
     12 if __name__ == "__main__":
---> 13     main()

<ipython-input-6-e399e2b5b40c> in main()
      1 def main():
----> 2     sf = FS.Select(Sequence = False, Random = True, Cross = False) #select the way you want to process searching
      3     sf.ImportDF(prepareData(),label = 'is_attributed')
      4     sf.ImportLossFunction(modelscore,direction = 'descend')
      5     sf.ImportCrossMethod(CrossMethod)

AttributeError: module 'MLFeatureSelection' has no attribute 'Select'

**Comment by duxuhao** [comment]
请问你是通过pip安装的吗？如果是通过pip安装的话，导入的时候需要将demo.py
import FeatureSelection as FS
改为
from MLFeatureSelection import FeatureSelection as FS
pip安装的例子请参见
https://pypi.org/project/MLFeatureSelection/

我很快会修改这个bug

**Comment by RainFung** [comment]
已经修复成功,您好 我现在数据集有100维特征,跑一次结果需要1个小时,请问怎么有效的设置参数呢?

**Comment by rain1zhi** [comment]
请问能加你QQ联系您么,我QQ9654592,对您的这个工具很感兴趣

**Comment by duxuhao** [comment]
不好意思，我的这个代码暂时比较暴力，运行时间花的是比较长，主要的限制是每次模型的运行时间，代码还在优化当中，后期会考虑怎么提升速度的
