### ISSUE TITLE
维度高的时候，计算的时间太长

### ISSUE THREAD

**Issue by Lvnszn** [duxuhao/Feature-Selection#5]
你好，我用了一下，面对这样的情况320个特征，15w数据，用kfold的话，不做交叉，速度没有我达到我预期。
我想确认一下复杂度，假设有30个特征，这样的话大概要跑多少轮？

**Comment by duxuhao** [comment]
你好，谢谢反馈！这个速度主要取决你单次模型的运行时间，如果你单次模型运行需要10秒，320个特征跑一圈就是直接乘了得到3200秒了。速度是不快，我在考虑添加并行的功能。

**Comment by duxuhao** [comment]
如果没什么其他问题我就close了，谢谢
