### ISSUE TITLE
win10正常运行，Ubuntu报错

### ISSUE THREAD

**Issue by InvictusY** [duxuhao/Feature-Selection#7]
Features Quantity Limit: inf
Time Limit: inf min(s)
Traceback (most recent call last):
  File "xulie.py", line 69, in <module>
    main()
  File "xulie.py", line 66, in main
    sf.run(validation)
  File "/home/dc2-user/anaconda3/lib/python3.5/site-packages/MLFeatureSelection/FeatureSelection.py", line 470, in run
    columnname = self.ColumnName[:],
AttributeError: 'Select' object has no attribute 'ColumnName'
请问这是怎么回事呢？

**Comment by duxuhao** [comment]
神奇，我一直都是在ubuntu下面搞的，问一下您跑sf.GenerateCol()了吗？你现在的版本号是多少？

**Comment by InvictusY** [comment]
我是跑的demo_IJCAI_2018.py 这个，把里面的数据集换成了我自己的，在win10下，可以正常跑，也可以出结果，但是放到云服务器上，就会报上面那个错，我没找到sf.GenerateCol()这个

**Comment by InvictusY** [comment]
对了ubuntu 是16.04

**Comment by InvictusY** [comment]
谢谢大神，已经解决了，可以正常运行了，但是我还有一个疑问，用代码选择出来的特征，然后放进原来的模型，损失怎么要比特征选择时显示的损失要高一些呢？

**Comment by duxuhao** [comment]
之前一直没看到😂，一般损失出来是一样的，可能会是sample设置不为1导致的？

**Comment by duxuhao** [comment]
谢谢你的提醒，是pandas.DataFrame.sample在设置的时候的原因，已经修复了。
